= Tools for converting DocBook to AsciiDoc

This directory contains the tools that were used to do the initial automatic conversion to AsciiDoc. Note that these tools are here for development purposes and are __not complete__. This conversion process will undoubtedly be arcane and require tools that won't be listed here, since it is not meant to be done by anyone other than myself.

What follows is some information about the attempts to automatically convert DocBook to AsciiDoc.

== Information Not Converted By Pandoc

* The title/short description
* The function synopsis section
* Some inline math functions (delimited by `$` characters in a paragraph without any XML or latexmath: markup).
* Any `+citerefentry+` cross-links.
* Versions.
* Inclusions of tables.

Necessary tools:

* Conversion for the DocBook XML files:
** Pandoc DocBook 5 to AsciiDoc.
** Extract the title/description to a separate file.
** Extract the function synopsis section to a separate file.
* Search DocBook XML files:
** All `+citerefentry+` cross-links and the files they come from.
** All `xi:include`sions.
* Search AsciiDoc output:
** Find files containing `+$...$+` that are not prefixed by `+latexmath:+` notation.
* Transformations for Pandoc output files:
** Convert Pandoc output to more standard block notation `+= title+` rather than `title\n-----` notation.
** Remove everything before the "Parameters" section.
** Prepend any `+latexmath:[+` tags with `+[eq]+`.
** Merge the direct Pandoc outputs with the ancillary files generated from DocBook.
* Generate an index page.

== Pandoc to Initial DocBook XML

This tool takes a source directory and a destination directory.

=== Collation

We begin by collating the list of files and information about them. For each "*.xml" file in the source directory, perform the following action:

* Parse the file as XML, without XInclusion. Print errors for any non-XML files.
* If the root element is `refentry`, build a data structure for a documented function. This structure should be added to a map of base filenames to data structures. This process includes:
** Store the filename in the list of source files.
** Extract the textual abstract (from the `refnamediv`) and the function names (from `refsynopsisdiv`). Store this in the data structure.
** From the `refsynopsisdiv` element, extract the function names, parameters, and return types. Store this in the data structure.
** Find any `citerefentry` elements, extract their text and the text of what they link to, and store this in the data structure.
** Find any `xi:include` elements, get their target files, and store them in the data structure.
** Store the type of the file. A file's type is a GLSL function, GLSL variable, or a GL function.
* If the root element is anything else, then the XML is an included file. Build a data structure for such files. This process includes:
** Store this (source) filename in a list of included files.
** Find any `citerefentry` elements, extract what they link to, and store this in the included file.

Integrity checks:

* Verify that files `xi:include`d actually exist and are in our lists.
* Verify that files which are detected as included are actually included by some file.
* Verify that any cited files actually exist.

=== DocBook Transformation

The next step is to copy the DocBook source files to a temporary directory. Hwoever, this copy needs to modify the source files appropriately before Pandoc gets a crack at them.

For main files, we must do the following:

* Remove all `xi:include` elements. Any includes that go to non-version/header files  should be replaced with AsciiDoctor textual includes of the equivalent generated file.

* Remove any `refsect` elements with an `xml:id` of `versions` or `seealso`.

=== Pandoc Transformation

=== AsciiDoctor Addendums

** Perform the Pandoc conversion of the file to the destination directory. Store the name of the destination file in the data structure.

** Perform the Pandoc conversion of the file to the destination directory. The name of the destination file should be prefixed by `inc_`.

